// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: vermouth_rpc_service.proto

package vermouth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterToProxyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port        int64  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Prefix      string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	BalanceMode string `protobuf:"bytes,3,opt,name=balanceMode,proto3" json:"balanceMode,omitempty"` // 如果 prefix 不存在，使用 balanceMode 参数创建
	Static      bool   `protobuf:"varint,4,opt,name=static,proto3" json:"static,omitempty"`          // 同 3
	LocalAddr   string `protobuf:"bytes,5,opt,name=localAddr,proto3" json:"localAddr,omitempty"`     // 要注册的地址
}

func (x *RegisterToProxyReq) Reset() {
	*x = RegisterToProxyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vermouth_rpc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterToProxyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterToProxyReq) ProtoMessage() {}

func (x *RegisterToProxyReq) ProtoReflect() protoreflect.Message {
	mi := &file_vermouth_rpc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterToProxyReq.ProtoReflect.Descriptor instead.
func (*RegisterToProxyReq) Descriptor() ([]byte, []int) {
	return file_vermouth_rpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterToProxyReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterToProxyReq) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *RegisterToProxyReq) GetBalanceMode() string {
	if x != nil {
		return x.BalanceMode
	}
	return ""
}

func (x *RegisterToProxyReq) GetStatic() bool {
	if x != nil {
		return x.Static
	}
	return false
}

func (x *RegisterToProxyReq) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

type CancalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port      int64  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Prefix    string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	LocalAddr string `protobuf:"bytes,3,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
}

func (x *CancalReq) Reset() {
	*x = CancalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vermouth_rpc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancalReq) ProtoMessage() {}

func (x *CancalReq) ProtoReflect() protoreflect.Message {
	mi := &file_vermouth_rpc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancalReq.ProtoReflect.Descriptor instead.
func (*CancalReq) Descriptor() ([]byte, []int) {
	return file_vermouth_rpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *CancalReq) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CancalReq) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CancalReq) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

type JoinClusterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName   string `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	TcpAddress string `protobuf:"bytes,2,opt,name=tcpAddress,proto3" json:"tcpAddress,omitempty"`
}

func (x *JoinClusterReq) Reset() {
	*x = JoinClusterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vermouth_rpc_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterReq) ProtoMessage() {}

func (x *JoinClusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_vermouth_rpc_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterReq.ProtoReflect.Descriptor instead.
func (*JoinClusterReq) Descriptor() ([]byte, []int) {
	return file_vermouth_rpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *JoinClusterReq) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *JoinClusterReq) GetTcpAddress() string {
	if x != nil {
		return x.TcpAddress
	}
	return ""
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vermouth_rpc_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_vermouth_rpc_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_vermouth_rpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *Res) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vermouth_rpc_service_proto protoreflect.FileDescriptor

var file_vermouth_rpc_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x70, 0x63, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x76, 0x65,
	0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x98, 0x01, 0x0a, 0x12,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x20,
	0x0a, 0x0b, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x22, 0x55, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x22, 0x4c, 0x0a,
	0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1f, 0x0a, 0x03, 0x52,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd2, 0x01, 0x0a,
	0x0c, 0x56, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x47, 0x72, 0x70, 0x63, 0x12, 0x48, 0x0a,
	0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x12, 0x21, 0x2e, 0x76, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x6f, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x76, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x12, 0x18, 0x2e, 0x76, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x76, 0x65,
	0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x12,
	0x40, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1d,
	0x2e, 0x76, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x76, 0x65, 0x72, 0x6d, 0x6f, 0x75, 0x74, 0x68, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_vermouth_rpc_service_proto_rawDescOnce sync.Once
	file_vermouth_rpc_service_proto_rawDescData = file_vermouth_rpc_service_proto_rawDesc
)

func file_vermouth_rpc_service_proto_rawDescGZIP() []byte {
	file_vermouth_rpc_service_proto_rawDescOnce.Do(func() {
		file_vermouth_rpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_vermouth_rpc_service_proto_rawDescData)
	})
	return file_vermouth_rpc_service_proto_rawDescData
}

var file_vermouth_rpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vermouth_rpc_service_proto_goTypes = []interface{}{
	(*RegisterToProxyReq)(nil), // 0: vermouth_grpc.RegisterToProxyReq
	(*CancalReq)(nil),          // 1: vermouth_grpc.CancalReq
	(*JoinClusterReq)(nil),     // 2: vermouth_grpc.JoinClusterReq
	(*Res)(nil),                // 3: vermouth_grpc.Res
}
var file_vermouth_rpc_service_proto_depIdxs = []int32{
	0, // 0: vermouth_grpc.VermouthGrpc.RegisterToProxy:input_type -> vermouth_grpc.RegisterToProxyReq
	1, // 1: vermouth_grpc.VermouthGrpc.Cancel:input_type -> vermouth_grpc.CancalReq
	2, // 2: vermouth_grpc.VermouthGrpc.JoinCluster:input_type -> vermouth_grpc.JoinClusterReq
	3, // 3: vermouth_grpc.VermouthGrpc.RegisterToProxy:output_type -> vermouth_grpc.Res
	3, // 4: vermouth_grpc.VermouthGrpc.Cancel:output_type -> vermouth_grpc.Res
	3, // 5: vermouth_grpc.VermouthGrpc.JoinCluster:output_type -> vermouth_grpc.Res
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vermouth_rpc_service_proto_init() }
func file_vermouth_rpc_service_proto_init() {
	if File_vermouth_rpc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vermouth_rpc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterToProxyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vermouth_rpc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vermouth_rpc_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vermouth_rpc_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vermouth_rpc_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vermouth_rpc_service_proto_goTypes,
		DependencyIndexes: file_vermouth_rpc_service_proto_depIdxs,
		MessageInfos:      file_vermouth_rpc_service_proto_msgTypes,
	}.Build()
	File_vermouth_rpc_service_proto = out.File
	file_vermouth_rpc_service_proto_rawDesc = nil
	file_vermouth_rpc_service_proto_goTypes = nil
	file_vermouth_rpc_service_proto_depIdxs = nil
}
